spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379


unleash:
  api-url: ${UNLEASH_API_URL}
  api-key: ${UNLEASH_API_KEY}
  admin-api-url: ${UNLEASH_ADMIN_API_URL}
  admin-api-key: ${UNLEASH_ADMIN_API_KEY}
  app-name: ff-demo
